version: 0.2
env:
  variables:
    OWNER_NAME: "Adityansh9109"              # Organization name
    REPO_NAME: "codebuild29-10-final-gitdiff-2"
    BRANCH_NAMES: "dev,qa"                 # Branches to create
    USERS: "AdityanshShamra"             # GitHub usernames
  secrets-manager:
    GITHUB_TOKEN: "myapp/github-token:GITHUB_TOKEN"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install PyGithub

  pre_build:
    commands:
      - echo "🔍 Checking if new code changes are present..."
      - |
        # Try to detect git information if available
        if [ -d .git ]; then
          echo "Git repository found, checking diff..."
          git diff --quiet || GIT_CHANGED=$?
        else
          echo "⚠️ No .git directory found (artifact from CodePipeline)."
          echo "Assuming source has changed since pipeline triggered."
          GIT_CHANGED=1
        fi

        if [ "$GIT_CHANGED" = "1" ]; then
          echo "✅ Changes detected — continuing with deployment..."
        else
          echo "🟡 No code changes detected — skipping deployment."
          exit 0
        fi

  build:
    commands:
      - echo "🚀 Running create_repo.py..."
      - python create_repo.py

  post_build:
    commands:
      - echo "✅ Repository creation completed successfully."
