version: 0.2
env:
  variables:
    OWNER_NAME: "Adityansh9109"              # Organization name
    REPO_NAME: "codebuild16-10"
    BRANCH_NAMES: "dev,qa"                 # Branches to create
    USERS: "AdityanshShamra"             # GitHub usernames
  secrets-manager:
    GITHUB_TOKEN: "myapp/github-token:GITHUB_TOKEN"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install PyGithub

  build:
    commands:
      - echo "Running create_repo.py..."
      - python create_repo.py

  post_build:
    commands:
      - echo "✅ Repository creation completed."
